name: Generate TOC

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  generate_toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/toc-generator@v3  # Update to v3
        with:
          FOLDING: false